performance_test_engineer_task:
  description: >
    Please extract input params no_of_requests, method and URL from {task_description} and complete the task
  expected_output: >
    Please display success if all requests are successfull else print fail
  agent: performance_test_engineer
